import Link from 'next/link'

import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Auth Udemy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex justify-between gap-5 items-center'>
          <h1>Next Auth</h1>
          <div className='flex gap-5 items-center'>             
             <Link href='/'>Home</Link>
             <Link href='/login'>Login</Link>
             <Link href='/register'>Register</Link>
             <Link href='/profile'>Profile</Link>
          </div>
          </div>
        {children}
        <h1>Footer</h1>
        </body>
    </html>
  )
}
